### ISSUE TITLE
: execution reverted: "Invalid admin signature"

### ISSUE THREAD

**Issue by datasonglook** [dante4rt/plume-testnet-bot#3]
Preparing transaction...
[22:28:08] Transaction error: execution reverted: "Invalid admin signature"
Retrying in 10 seconds...
Starting the faucet claiming process...

**Comment by dante4rt** [comment]
> Preparing transaction... [22:28:08] Transaction error: execution reverted: "Invalid admin signature" Retrying in 10 seconds... Starting the faucet claiming process...

Its fixed already.
