### ISSUE TITLE
[20:26:47] Transaction error: execution reverted: "Invalid admin signature"

### ISSUE THREAD

**Issue by Pawansingh333** [dante4rt/plume-testnet-bot#4]
[20:26:47] Transaction error: execution reverted: "Invalid admin signature"

**Comment by dante4rt** [comment]
> [20:26:47] Transaction error: execution reverted: "Invalid admin signature"

Give me steps to re-produce the error.

**Comment by Pawansingh333** [comment]
Done

**Comment by dante4rt** [comment]
> Done

Aight.
